In [6]:
import numpy as np

In [2]:
import pandas as pd
pd.DataFrame({'A':[1,2,3]})

   A
0  1
1  2
2  3

In [3]:
a=1

In [4]:
a

1

In [7]:
s=pd.Series([1,3,5,np.nan,6,8])

In [8]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [9]:
dates = pd.date_range("20130101", periods=6)

In [10]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [11]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

In [12]:
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [13]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [14]:
df2.add

<bound method DataFrame.add of      A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo>

In [16]:
df2.head()

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [18]:
df2.tail(2)

     A          B    C  D      E    F
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [20]:
df2.index

Index([0, 1, 2, 3], dtype='int64')

In [21]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [22]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [23]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [24]:
df2.describe()

         A                    B    C    D
count  4.0                    4  4.0  4.0
mean   1.0  2013-01-02 00:00:00  1.0  3.0
min    1.0  2013-01-02 00:00:00  1.0  3.0
25%    1.0  2013-01-02 00:00:00  1.0  3.0
50%    1.0  2013-01-02 00:00:00  1.0  3.0
75%    1.0  2013-01-02 00:00:00  1.0  3.0
max    1.0  2013-01-02 00:00:00  1.0  3.0
std    0.0                  NaN  0.0  0.0

In [26]:
df2.T

,0,1,2,3
A,1.0,1.0,1.0,1.0
B,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00,2013-01-02 00:00:00
C,1.0,1.0,1.0,1.0
D,3,3,3,3
E,test,train,test,train
F,foo,foo,foo,foo

In [27]:
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [28]:
df2.sort_index(axis=1, ascending=False)

     F      E  D    C          B    A
0  foo   test  3  1.0 2013-01-02  1.0
1  foo  train  3  1.0 2013-01-02  1.0
2  foo   test  3  1.0 2013-01-02  1.0
3  foo  train  3  1.0 2013-01-02  1.0

In [29]:
df2.sort_values(by="B")

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

## Selection

In [30]:
df2['A']

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [31]:
df2.A

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [32]:
df2[['B', 'A']]

           B    A
0 2013-01-02  1.0
1 2013-01-02  1.0
2 2013-01-02  1.0
3 2013-01-02  1.0

In [33]:
df2[0:3]

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo

In [37]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

In [39]:
df

                   A         B         C         D
2013-01-01  0.853757 -0.536522  0.348448  0.259015
2013-01-02 -0.245908 -0.194174  0.375606  1.283898
2013-01-03 -0.627390  0.278126  0.611421 -0.721866
2013-01-04  0.306547 -0.412203 -0.973739  0.130532
2013-01-05  0.203389  1.245556  0.254057 -1.223585
2013-01-06 -0.195686  0.115979  0.273886 -1.047656

Access a group of rows and columns by label(s) or a boolean array.

.loc[] is primarily label based, but may also be used with a boolean array.

Allowed inputs are:

A single label, e.g. 5 or 'a', (note that 5 is interpreted as a label of the index, and never as an integer position along the index).

A list or array of labels, e.g. ['a', 'b', 'c'].

A slice object with labels, e.g. 'a

In [38]:
df.loc[dates[0]]

A    0.853757
B   -0.536522
C    0.348448
D    0.259015
Name: 2013-01-01 00:00:00, dtype: float64

In [40]:
df.loc[:, ["A", "B"]]

                   A         B
2013-01-01  0.853757 -0.536522
2013-01-02 -0.245908 -0.194174
2013-01-03 -0.627390  0.278126
2013-01-04  0.306547 -0.412203
2013-01-05  0.203389  1.245556
2013-01-06 -0.195686  0.115979

In [41]:
df.loc["20130102":"20130104", ["A", "B"]]

                   A         B
2013-01-02 -0.245908 -0.194174
2013-01-03 -0.627390  0.278126
2013-01-04  0.306547 -0.412203

In [42]:
df.loc[dates[0], "A"]

np.float64(0.8537572709077298)

In [43]:
df.at[dates[0], "A"]

np.float64(0.8537572709077298)

In [44]:
df.iloc[3]

A    0.306547
B   -0.412203
C   -0.973739
D    0.130532
Name: 2013-01-04 00:00:00, dtype: float64

In [45]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04  0.306547 -0.412203
2013-01-05  0.203389  1.245556

In [46]:
df

                   A         B         C         D
2013-01-01  0.853757 -0.536522  0.348448  0.259015
2013-01-02 -0.245908 -0.194174  0.375606  1.283898
2013-01-03 -0.627390  0.278126  0.611421 -0.721866
2013-01-04  0.306547 -0.412203 -0.973739  0.130532
2013-01-05  0.203389  1.245556  0.254057 -1.223585
2013-01-06 -0.195686  0.115979  0.273886 -1.047656

In [48]:
df.iloc[3:,2:]

                   C         D
2013-01-04 -0.973739  0.130532
2013-01-05  0.254057 -1.223585
2013-01-06  0.273886 -1.047656

In [49]:
df.iloc[[1,2,4], [0,2]]

                   A         C
2013-01-02 -0.245908  0.375606
2013-01-03 -0.627390  0.611421
2013-01-05  0.203389  0.254057

In [50]:
df.iloc[1:3,:]

                   A         B         C         D
2013-01-02 -0.245908 -0.194174  0.375606  1.283898
2013-01-03 -0.627390  0.278126  0.611421 -0.721866

In [51]:
df.iloc[:,1:3]

                   B         C
2013-01-01 -0.536522  0.348448
2013-01-02 -0.194174  0.375606
2013-01-03  0.278126  0.611421
2013-01-04 -0.412203 -0.973739
2013-01-05  1.245556  0.254057
2013-01-06  0.115979  0.273886

In [52]:
df.iloc[1,1]

np.float64(-0.19417394793165915)

In [53]:
df.iat[1,1]

np.float64(-0.19417394793165915)

### Boolean Indexing

In [54]:
df[df["A"] > 0]

                   A         B         C         D
2013-01-01  0.853757 -0.536522  0.348448  0.259015
2013-01-04  0.306547 -0.412203 -0.973739  0.130532
2013-01-05  0.203389  1.245556  0.254057 -1.223585

In [55]:
df[df>0]

                   A         B         C         D
2013-01-01  0.853757       NaN  0.348448  0.259015
2013-01-02       NaN       NaN  0.375606  1.283898
2013-01-03       NaN  0.278126  0.611421       NaN
2013-01-04  0.306547       NaN       NaN  0.130532
2013-01-05  0.203389  1.245556  0.254057       NaN
2013-01-06       NaN  0.115979  0.273886       NaN

In [56]:
df

                   A         B         C         D
2013-01-01  0.853757 -0.536522  0.348448  0.259015
2013-01-02 -0.245908 -0.194174  0.375606  1.283898
2013-01-03 -0.627390  0.278126  0.611421 -0.721866
2013-01-04  0.306547 -0.412203 -0.973739  0.130532
2013-01-05  0.203389  1.245556  0.254057 -1.223585
2013-01-06 -0.195686  0.115979  0.273886 -1.047656

In [57]:
df2=df.copy()